### ISSUE TITLE
Question about Unity Input and ENet Thread Safety

### ISSUE THREAD

**Issue by valkyrienyanko** [SoftwareGuy/ENet-CSharp#28]
ENet is said to generally be not thread safe. So how would you do `peer.Send(...)` outside of the thread worker? For example, lets say I want to send a packet when someone presses the `R` key with `Input.GetKeyDown(KeyCode.R)` in Unity's `void Update()` loop. This could only be possible if `Peer peer` was defined outside the scope of the thread worker.

*Please refer to the issue linked below for more details.*

https://github.com/Kittens-Rise-Up/client/issues/1

**Comment by SoftwareGuy** [comment]
Hey there, thanks for the excellent question. :wave:

The way I've done a similar thing is use a ConcurrentQueue that utilizes a struct that contains the needed information. That way, you just let the ENet worker thread dispatch them as soon as it receives it in the queue. Don't put a struct inside a struct though, that can become ugly really fast (and isn't good for CPU cache instructions).

So, in summary:

If user presses R, then:

1. Unity runs the code responsible for pressing R.
2. Enqueue the data into the queue.
3. ENet worker thread runs and uses Queue.TryDequeue() in a while loop to make sure that queue is emptied ASAP.

If you really need to make the Peer object accessible, one option you could pursue is to do the networking in the main thread rather than a separate thread. The problem there is if Unity's main thread is bogged down, ENet will also be affected vs having ENet in a seperate thread allowing it to run independently.

 I have not tried using the C# `volatile` option, which makes a object like Peer possible be shared between threads, but this can cause overhead and is not considered to be best practice unless absolutely needed. Peer is apparently a safe/unsafe mix, some properties are safe, some use native ENet calls that may crash if attempted to be run outside the thread powering it.

**Comment by valkyrienyanko** [comment]
Why do you drain the queues in Start()?

https://github.com/SoftwareGuy/Ignorance/blob/d1c38648766445196baec1376b03815f47c90f2a/Assets/Mirror/Runtime/Transport/Ignorance/Core/IgnoranceClient.cs#L69

Don't you only need a `ConcurrentQueue` for `Commands` in Client? *(because there needs to be a thread safe way for transferring data between threads)*. Are the other queues for Incoming / Outgoing necessary?

Do you have queues for Incoming / Outgoing just so you can have everything "queued"? So nothing is missed? Everything is lined up in a queue?

Are specifically concurrent queues needed here? Could some other kind of queue be used?

**Comment by SoftwareGuy** [comment]
>Why do you drain the queues in Start()? ...

@valkyrienyanko The queues are drained in Start() to ensure that there is no left over events or data that would be processed straight out the door when the Transport begins its work and passes things back to Mirror. Without it, I found that Mirror may process old data and have a bit of a freak out with a bunch of warnings about unknown objects, etc. 

In older versions of my transport, I forgot to clear them and you’d randomly get some entries in the queue that are random bad data. So that’s why I drain them in Start, so everything is clean.

As for commands in client, queues are not bidirectional, so I can’t just have one queue running the whole show. I potentially could with hackery but I’m more interested in having a stable and known-good implementation than something experimental. 😅 Although, with that said, you have given me an idea… (insert galaxy brain meme here)

You don’t have to use ConcurrentQueues. I just used them as they’re built-in and thread safe with NET 4.x/Core/Standard. Other options include RingBuffers. As long as it’s thread safe, you can do whatever you like with your queue implementation, be it a Ring Buffer, a ConcurrentQueue or something more exotic.

**Comment by valkyrienyanko** [comment]
> As for commands in client, queues are not bidirectional, so I can’t just have one queue running the whole show.

Not sure what you mean by this.

I meant couldn't you do everything directly in here? https://github.com/SoftwareGuy/Ignorance/blob/d1c38648766445196baec1376b03815f47c90f2a/Assets/Mirror/Runtime/Transport/Ignorance/Core/IgnoranceClient.cs#L236-L267

There's no need to pass the incoming packet to a queue, you could just create private methods in here to handle the packets being received. Unless you wanted to handle the packets else where and be more organized? It can get messy if everything is done in one file. I remember using reflection to solve this problem, but a queue seems much nicer. I'm just wondering would problems arise if queues were not used for incoming / outgoing packets?

**Comment by SoftwareGuy** [comment]
You forget that I'm interfacing with Mirror, which is running in the main Unity thread. I cannot simply just call Mirror's handlers from the thread since they are not thread safe. That would potentially cause crashes because of inter-thread communication and access violations.

Anyway, this is going outside the realm of ENet-CSharp itself and more into my implementation of a ENet-CSharp based transport so let's continue the Ignorance implementation discussion over on the Ignorance repo, because you're onto some good points. 😃

**Comment by valkyrienyanko** [comment]
Sorry, if I have any more questions about your mirror transport I'll be sure to create a discussion over there from now on.

You have helped me out a ton and I almost feel guilty asking all these questions. I have a much better understanding of thread safety now. You are the best, thank you.

**Comment by SoftwareGuy** [comment]
I should be thanking you for the discussion - I appreciate the questions. You've pointed out some interesting things too, so it's a win-win. 😄
