### ISSUE TITLE
Errors on Build / Export Godot Project

### ISSUE THREAD

**Issue by valkyrienyanko** [SoftwareGuy/ENet-CSharp#36]
![image](https://user-images.githubusercontent.com/6277739/149005620-cf2a1e77-7bf7-4738-910c-1e80186ac0d5.png)

This error happens when I try to build / export my Godot project.

I found this error on the web that was similar to mine  https://godotengine.org/qa/85919/godot-mono-export-cannot-load-assembly-refonly-xamarin-please except theirs had something to do with iOS related.

I've never had this issue when building / exporting on `main` branch, this only started happening when I decided to start all over on `dev` branch. Repo: https://github.com/Raccoons-Rise-Up/client-godot

Steps to Reproduce
Clone `dev` branch from https://github.com/Raccoons-Rise-Up/client-godot and export project. Errors should appear on project export.

.csproj
![image](https://user-images.githubusercontent.com/6277739/149006020-d2dc5689-4101-4908-9b44-f9a7fa4d33f1.png)

NuGet packages viewed in Visual Studio Community
![image](https://user-images.githubusercontent.com/6277739/149006430-d165f1a5-eb17-4ffd-b21d-8acc4a51c4be.png)

Included ENet files
![image](https://user-images.githubusercontent.com/6277739/149006166-0df48818-395a-4d36-a831-0ce8a8c0c40c.png)

I'm running on Windows 10 64 bit.

**Comment by valkyrienyanko** [comment]
Could this be why?

![image](https://user-images.githubusercontent.com/6277739/149023723-4447bb24-f692-42a1-babd-eebd2c65bd09.png)

**Comment by valkyrienyanko** [comment]
![image](https://user-images.githubusercontent.com/6277739/149028520-62d401fa-4f7f-4a51-a4c9-2d570bab87aa.png)

**Comment by valkyrienyanko** [comment]
![image](https://user-images.githubusercontent.com/6277739/149028557-1c93d2d9-4d64-4c00-b2e6-76dc1d9c622b.png)

**Comment by SoftwareGuy** [comment]
While ENet-CSharp may work with Godot, I can not support Godot. From what I'm seeing, it's using some wrappers to offer C# functionality?

In addition, that error about being unable to load GodotSharp is outside the scope of this support ticket. You are much better off asking for help regarding that in either the Godot Discord or a support forum.

Check the following:
- Your runtime for Godot is the same CPU architecture as the ENet binary. Unless otherwise stated, the MSBuild system in this repository builds for x86_64 CPUs. **You cannot load 32bit DLLs into a 64bit application or vice versa.**
- Godot isn't expecting the DLL (library) file in some obscure location or prefix like "libenet" instead of just "enet". Try placing the DLL in the root with the EXE file of your project and see if that works.
- Looks like the Net Standard 2.1 target runtime library is missing and Godot is complaining about it?

Sorry that I can't be of much help, I don't use Godot and outside of the above tips, I dunno.

**Comment by valkyrienyanko** [comment]
I solved it by including ENet-CSharp.dll (grabbed from https://github.com/nxrighthere/ENet-CSharp/releases) locally instead of through NuGet.

```xml
<Project Sdk="Godot.NET.Sdk/3.3.0">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>Client</RootNamespace>
	<DefineConstants>CLIENT;</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <NoWarn>1701;1702</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <!--<PackageReference Include="ENet-CSharp" Version="2.4.7" />-->
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <Reference Include="ENet-CSharp">
        <HintPath>ENet-CSharp.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
```

Commented out code is how I was doing it before.

Maybe the ENet-CSharp provided through nxrighthere enet csharp releases is running on a different CPU architecture as suppose to the one he provides though NuGet. I'm not sure how to check these things. I'm very weak in this area, however I'm glad I figured out a solution as I spent all day trying to figure this out.

**Comment by valkyrienyanko** [comment]
Now I'm running into a different problem. Exporting the game is fine. But now the code won't go past this `ENet.Library.Initialize();` function. `"B"` simply won't be logged in exported release (however it works fine in Godot editor)

![image](https://user-images.githubusercontent.com/6277739/149048437-cecf7cd0-2498-4ba0-ae23-f4bfee031bd5.png)

**Comment by valkyrienyanko** [comment]
Okay nvm solved it's because I forgot to include `enet.dll` in exported release folder.
