### ISSUE TITLE
What are the differences?

### ISSUE THREAD

**Issue by duuuuuuuuuuude** [SoftwareGuy/ENet-CSharp#37]
from the README:

> an independent ENet native implementation with a _modified_ protocol

What does "_modified_" mean in this sentence?

Does it mean that this library is not compatible with the original enet at http://enet.bespin.org? that the protocol used here is different?

**Comment by valkyrienyanko** [comment]
All I know is the libraries from http://enet.bespin.org/ will not work with this modified version of ENet. Hope that helps.

**Comment by dluc** [comment]
that helps yes, because I was blocked, trying to make this work with a third party app that probably uses the other enet implementation.  Is there a reason for the incompatibility? I was curious to understand if this library provides some improvements, or if it just happens to be different because of implementation details. It's a bit confusing finding multiple "enet" libraries that cannot work together, in particular with dealing with third party apps.

**Comment by SoftwareGuy** [comment]
Basically, it's a different protocol version. Bespin's ENet is protocol version 1.x and this fork (plus upstream) modified it, improving things and adding some quality of life fixes. That's why it's incompatible between ENet 1.x and 2.x.

**Comment by duuuuuuuuuuude** [comment]
This info is very useful indeed, I was trying to make this lib work with an app that uses enet, expecting it to work. If you can, it would be nice mentioning this incompatibility more explicitly in the README. For instance, it's great to say this library provides improvements but also that it won't work with existing apps/services that use the C/C++ enet library. Thanks!
